In [1]:
import sys
import yaml

In [19]:
def change(data):
    data['TEST']['DATA']['DO_PREPROCESS'] = True

    data['TEST']['DATA']['DATA_PATH'] = 'E:/FirstProj/mcd_rppg'
    data['TEST']['DATA']['CACHED_PATH'] = './data/Custom_cached'

    data['TEST']['DATA']['BEGIN'] = 0.0
    data['TEST']['DATA']['END'] = 0.001
    data['TEST']['DATA']['DO_PREPROCESS'] = True

    data['TEST']['DATA']['DATA_PATH'] = 'E:/FirstProj/mcd_rppg'
    data['TEST']['DATA']['CACHED_PATH'] = './data/Custom_cached'

    data['TEST']['DATA']['BEGIN'] = 0.0
    data['TEST']['DATA']['END'] = 0.001

    data['TEST']['DATA']['PREPROCESS']['CROP_FACE']['BACKEND'] = 'MP'
    return data

In [17]:
import glob
import os


for i in glob.glob('./CustomConfigs/*.yaml'):
    with open(i) as fp:
        data = yaml.load(fp,Loader=yaml.FullLoader)
        data = change(data)
        fp.close()
    with open(i , "w") as f:
        yaml.dump(data, f)
    os.system(f'python main.py --config_file {i}')

{'BASE': [''],
 'TOOLBOX_MODE': 'only_test',
 'TEST': {'METRICS': ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA', 'MACC'],
  'USE_LAST_EPOCH': False,
  'DATA': {'FS': 30,
   'DATASET': 'MCD-rPPG',
   'DO_PREPROCESS': True,
   'DATA_FORMAT': 'NCDHW',
   'DATA_PATH': 'E:/FirstProj/mcd_rppg',
   'CACHED_PATH': './data/Custom_cached',
   'EXP_DATA_NAME': '',
   'BEGIN': 0.0,
   'END': 0.001,
   'PREPROCESS': {'DATA_TYPE': ['Raw'],
    'LABEL_TYPE': 'Standardized',
    'DO_CHUNK': True,
    'CHUNK_LENGTH': 160,
    'CROP_FACE': {'DO_CROP_FACE': True,
     'BACKEND': 'MP',
     'USE_LARGE_FACE_BOX': True,
     'LARGE_BOX_COEF': 1.5,
     'DETECTION': {'DO_DYNAMIC_DETECTION': True,
      'DYNAMIC_DETECTION_FREQUENCY': 30,
      'USE_MEDIAN_FACE_BOX': False}},
    'RESIZE': {'H': 72, 'W': 72}}}},
 'DEVICE': 'cpu',
 'NUM_OF_GPU_TRAIN': 1,
 'LOG': {'PATH': 'runs/exp'},
 'MODEL': {'DROP_RATE': 0.1,
  'NAME': 'iBVPNet',
  'iBVPNet': {'CHANNELS': 3, 'FRAME_NUM': 160}},
 'INFERENCE': {'BATCH_SIZE': 

In [2]:
LOCAL_DISK_MOUNT = 'E:\FirstProj\mcd_rppg'

<>:1: SyntaxWarning: invalid escape sequence '\F'
<>:1: SyntaxWarning: invalid escape sequence '\F'
C:\Users\XOPC\AppData\Local\Temp\ipykernel_19436\1636734756.py:1: SyntaxWarning: invalid escape sequence '\F'
  LOCAL_DISK_MOUNT = 'E:\FirstProj\mcd_rppg'


In [3]:
from huggingface_hub import snapshot_download
LOCAL_DISK_CACHE_DIR = f'{LOCAL_DISK_MOUNT}/hf_cache/'
snapshot_download(repo_id="kyegorov/mcd_rppg",local_dir=LOCAL_DISK_MOUNT,cache_dir=LOCAL_DISK_CACHE_DIR,repo_type="dataset")

Fetching 13204 files: 100%|██████████| 13204/13204 [2:51:53<00:00,  1.28it/s]  


'E:\\FirstProj\\mcd_rppg'

In [3]:
from rPPG_Toolbox.neural_methods.model import iBVPNet
import torch

In [14]:
model = iBVPNet.iBVPNet(160)
model.load_state_dict(torch.load('./rPPG_Toolbox/final_model_release/PURE_iBVPNet.pth',map_location='cpu'))

<All keys matched successfully>

In [15]:
model_scripted = torch.jit.script(model) # Export to TorchScript
model_scripted.save('model_scripted.pt') # Save

RuntimeError: Can't redefine method: forward on class: __torch__.rPPG_Toolbox.neural_methods.model.iBVPNet.iBVPNet (of Python compilation unit at: 00000168C1665AD0)

In [4]:
from datasets import load_dataset
 
LOCAL_DISK_CACHE_DIR = f'{LOCAL_DISK_MOUNT}/hf_cache/'
 
# set cache_dir to be in elastic disk
dataset = load_dataset("kyegorov/mcd_rppg", cache_dir=LOCAL_DISK_CACHE_DIR)

Generating train split: 2 examples [00:01,  1.25 examples/s]


DatasetGenerationError: An error occurred while generating the dataset

In [3]:
parser = rPPG_Toolbox.dataset.data_loader.BaseLoader

In [4]:
import numpy as np
from scipy.stats import gaussian_kde

In [14]:
np.matrix(xy)

matrix([[109.4941901 ,  88.8418154 ],
        [110.06596332,  92.24078273]])

In [19]:
xy = np.array([[109.4941901 ,  88.8418154 ],
       [110.06596332,  92.24078273]]).astype(np.float64)
#xy = np.matrix(xy)
gaussian_kde(xy)(xy)

array([52103.26720011, 52103.26720011])

In [21]:
np.linalg.eigh(np.cov(xy))[0]

array([1.42108547e-14, 3.72128822e+02])

In [23]:
np.eye(np.cov(xy))

TypeError: only integer scalar arrays can be converted to a scalar index